development:
  adapter: async
  url: redis://redistogo:9599a982b1b3bc038f6a7d400377e2c7@scat.redistogo.com:9316/

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9599a982b1b3bc038f6a7d400377e2c7@scat.redistogo.com:9316/
